// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpaceExplorer.API.Data;

#nullable disable

namespace SpaceExplorer.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("SpaceExplorer.API.Models.Planet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DiscoveryMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("DiscoveryYear")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("DistanceFromEarth")
                        .HasColumnType("REAL");

                    b.Property<double?>("Mass")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("OrbitalPeriod")
                        .HasColumnType("REAL");

                    b.Property<double?>("Radius")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Planets");
                });
#pragma warning restore 612, 618
        }
    }
}
